const quizData = [
    {
    question: "CSS stands for -",
    a: "Cascade style sheets",
    b: "Color and style sheets",
    c: "Cascading style sheets",
    d: "None of the above",
    correct: "c",
},
    {
    question: "Which of the following is the correct syntax to display the hyperlinks without any underline?",
    a: "a {text-decoration : underline;}",
    b: "a {decoration : no-underline;}",
    c: "a {text-decoration : none;}",
    d: "None of the above",
    correct: "c",
},
    {
    question: "Which of the following CSS property is used to make the text bold?",
    a: "text-decoration: bold",
    b: "font-weight: bold",
    c: "font-style: bold",
    d: "text-align: bold",
    correct: "b",
},
    {
    question: "We can make rounded borders around elements using which CSS element?",
    a: "border-collapse",
    b: "border-radius",
    c: "border-round",
    d: "None of the above",
    correct: "b",
},
    {
    question: "Which of the following syntax is correct in CSS to make each word of a sentence start with a capital letter?",
    a: "text-style : capital;",
    b: "transform : capitalize;",
    c: "text-transform : capital;",
    d: "text-transform : capitalize;",
    correct: "d",
},
//     {
//     question: "",
//     a: "",
//     b: "",
//     c: "",
//     d: "",
//     correct: "",
// },
];