const quizData = [
    {
        question: "What does HTML stand for?",
        a: "Hypertext Markup Language",
        b: "Hypertext Markdown Language",
        c: "Hyperloop Machine Language",
        d: "Hyperloop markup language",
        correct: "a",
    },
    {
        question: "Which of the following HTML element is used for creating an unordered list?",
        a: "<ui>",
        b: "<i>",
        c: "<em>",
        d: "<ul>",
        correct: "d",
    },
    {
        question: "Which of the following attribute is used to provide a unique name to an element?",
        a: "class",
        b: "id",
        c: "type",
        d: "None of the above",
        correct: "b",
    },
    {
        question: "A program in HTML can be rendered and read by -",
        a: "Web browser",
        b: "Server",
        c: "Interpreter",
        d: "None of the above",
        correct: "a",
    },
    {
        question: "which of the following are the attributes of the tag?",
        a: "method",
        b: "action",
        c: "Both (a) & (b)",
        d: "None of the above",
        correct: "c",
    },
    // {
    //     question: "",
    //     a: "",
    //     b: "",
    //     c: "",
    //     d: "",
    //     correct: "",
    // },
];