const quizData = [
    {
    question: "Which type of JavaScript language is ___",
    a: "Object-Oriented",
    b: "Object-Based",
    c: "Assembly-language",
    d: "High-level",
    correct: "b",
},
    {
    question: "Which one of the following also known as Conditional Expression:",
    a: "Alternative to if-else",
    b: "Switch statement",
    c: "If-then-else statement",
    d: "immediate if",
    correct: "d",
},
    {
    question: "When interpreter encounters an empty statements, what it will do:",
    a: "Shows a warning",
    b: "Prompts to complete the statement",
    c: "Ignores the statements",
    d: "Throws an error",
    correct: "c",
},
    {
    question: "Which of the following variables takes precedence over the others if the names are the same?",
    a: "Global variable",
    b: "The local element",
    c: "The two of the above",
    d: "None of the above",
    correct: "b",
},
    {
    question: "In the JavaScript, which one of the following is not considered as an error:",
    a: "Syntax error",
    b: "Missing of semicolons",
    c: "Division by zero",
    d: "Missing of Bracket",
    correct: "c",
},
//     {
//     question: "",
//     a: "",
//     b: "",
//     c: "",
//     d: "",
//     correct: "",
// },
];