const quizData = [
    {
    question: "What does PHP stand for?",
    a: "Hypertext Preprocessor",
    b: "Personal Home Page",
    c: "Pretext Hypertext Processor",
    d: "Hypertext markup Preprocessor",
    correct: "a",
},
    {
    question: "PHP is a ___ language?",
    a: "user-side scripting",
    b: "client-side scripting",
    c: "server-side scripting",
    d: "Both B and C",
    correct: "c",
},
    {
    question: " In which year php was created?",
    a: "1993",
    b: "1994",
    c: "1995",
    d: "1996",
    correct: "b",
},
    {
    question: "print statement can take ___ argument?",
    a: "1",
    b: "2",
    c: "3",
    d: "4",
    correct: "a",
},
    {
    question: "foreach loop is used to iterate over ___?",
    a: "number",
    b: "object",
    c: "function",
    d: "array",
    correct: "d",
},
//     {
//     question: "",
//     a: "",
//     b: "",
//     c: "",
//     d: "",
//     correct: "",
// },
];